CREATE SCHEMA DEMO;


DROP TABLE IF EXISTS DEMO."USER";
CREATE TABLE DEMO."USER"
(
    ID        VARCHAR(255) PRIMARY KEY,
    FIRSTNAME VARCHAR(255),
    LASTNAME  VARCHAR(255),
    EMAIL     VARCHAR(255),
    PASSWORD  VARCHAR(255)
);
INSERT INTO DEMO."USER"
VALUES (1, 'FIRSTNAME', 'LASTNAME', 'EMAIL', 'PASSWORD');
INSERT INTO DEMO."USER"
VALUES (2, 'FIRSTNAME', 'LASTNAME', 'EMAIL', 'PASSWORD');
INSERT INTO DEMO."USER"
VALUES (3, 'FIRSTNAME', 'LASTNAME', 'EMAIL', 'PASSWORD');

SELECT *
FROM DEMO."USER"
ORDER BY ID;

DROP TABLE IF EXISTS DEMO."COURSE";
CREATE TABLE DEMO."COURSE"
(
    ID          VARCHAR(255) PRIMARY KEY,
    NAME        VARCHAR(255),
    DESCRIPTION VARCHAR(255)
);
INSERT INTO DEMO."COURSE"
VALUES (1, 'NAME', 'DESCRIPTION');
INSERT INTO DEMO."COURSE"
VALUES (2, 'NAME', 'DESCRIPTION');
INSERT INTO DEMO."COURSE"
VALUES (3, 'NAME', 'DESCRIPTION');

SELECT *
FROM DEMO."COURSE"
ORDER BY ID;
